spring.application.name=RemoteLogMonitor
server.port=8080
# --- PostgreSQL Datasource Configuration ---
# Specifies the JDBC URL for the PostgreSQL database.
# Default port is typically 5432.
spring.datasource.url=jdbc:postgresql://localhost:5432/remote_logger?serverTimezone=Asia/Calcutta
# The username for the database.
spring.datasource.username=postgres
# The password for the database.
spring.datasource.password=postgres
# --- JPA and Hibernate Properties (Optional but Recommended) ---
# Allows To Hibernate to generate SQL optimized for PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Controls the schema generation behavior of Hibernate (e.g., update, create, create-drop, validate, none).
spring.jpa.hibernate.ddl-auto=create
# Displays the SQL queries in the console for debugging purposes.
spring.jpa.show-sql=true
# Formats the SQL output for better readability.
spring.jpa.properties.hibernate.format_sql=true



#Custom
api.key.secret=secretkey
